// NYC ZIP Code Ranges
// Manhattan: 10001-10282
// Bronx: 10451-10475
// Brooklyn: 11201-11256
// Queens: 11004-11697
// Staten Island: 10301-10314

export function isValidNYCZip(zip: string): boolean {
  const zipNum = parseInt(zip, 10);

  if (isNaN(zipNum) || zip.length !== 5) {
    return false;
  }

  // Manhattan
  if (zipNum >= 10001 && zipNum <= 10282) return true;

  // Staten Island (overlaps with some Manhattan)
  if (zipNum >= 10301 && zipNum <= 10314) return true;

  // Bronx
  if (zipNum >= 10451 && zipNum <= 10475) return true;

  // Brooklyn
  if (zipNum >= 11201 && zipNum <= 11256) return true;

  // Queens
  if (zipNum >= 11004 && zipNum <= 11697) return true;

  return false;
}

export const NYC_BOROUGHS = [
  "Manhattan",
  "Brooklyn",
  "Queens",
  "Bronx",
  "Staten Island",
] as const;

export type NYCBorough = (typeof NYC_BOROUGHS)[number];

export const BOROUGH_NEIGHBORHOODS: Record<NYCBorough, string[]> = {
  Manhattan: [
    "Battery Park City",
    "Chelsea",
    "Chinatown",
    "East Harlem",
    "East Village",
    "Financial District",
    "Flatiron District",
    "Gramercy",
    "Greenwich Village",
    "Hamilton Heights",
    "Harlem",
    "Hell's Kitchen",
    "Inwood",
    "Kips Bay",
    "Lenox Hill",
    "Lincoln Square",
    "Little Italy",
    "Lower East Side",
    "Marble Hill",
    "Midtown",
    "Midtown East",
    "Midtown West",
    "Morningside Heights",
    "Murray Hill",
    "NoHo",
    "NoMad",
    "Roosevelt Island",
    "SoHo",
    "Stuyvesant Town",
    "Sutton Place",
    "Tribeca",
    "Two Bridges",
    "Upper East Side",
    "Upper West Side",
    "Washington Heights",
    "West Village",
    "Yorkville",
  ],
  Brooklyn: [
    "Bath Beach",
    "Bay Ridge",
    "Bedford-Stuyvesant",
    "Bensonhurst",
    "Bergen Beach",
    "Boerum Hill",
    "Borough Park",
    "Brighton Beach",
    "Brooklyn Heights",
    "Brownsville",
    "Bushwick",
    "Canarsie",
    "Carroll Gardens",
    "Clinton Hill",
    "Cobble Hill",
    "Coney Island",
    "Crown Heights",
    "Cypress Hills",
    "Ditmas Park",
    "Downtown Brooklyn",
    "DUMBO",
    "Dyker Heights",
    "East Flatbush",
    "East New York",
    "East Williamsburg",
    "Flatbush",
    "Flatlands",
    "Fort Greene",
    "Gerritsen Beach",
    "Gowanus",
    "Gravesend",
    "Greenpoint",
    "Kensington",
    "Manhattan Beach",
    "Marine Park",
    "Midwood",
    "Mill Basin",
    "Navy Yard",
    "Park Slope",
    "Prospect Heights",
    "Prospect Lefferts Gardens",
    "Red Hook",
    "Sheepshead Bay",
    "South Slope",
    "Sunset Park",
    "Vinegar Hill",
    "Williamsburg",
    "Windsor Terrace",
  ],
  Queens: [
    "Arverne",
    "Astoria",
    "Bayside",
    "Bellerose",
    "Briarwood",
    "Cambria Heights",
    "College Point",
    "Corona",
    "Douglaston",
    "East Elmhurst",
    "Elmhurst",
    "Far Rockaway",
    "Floral Park",
    "Flushing",
    "Forest Hills",
    "Fresh Meadows",
    "Glen Oaks",
    "Glendale",
    "Hollis",
    "Howard Beach",
    "Jackson Heights",
    "Jamaica",
    "Jamaica Estates",
    "Kew Gardens",
    "Kew Gardens Hills",
    "Laurelton",
    "Little Neck",
    "Long Island City",
    "Maspeth",
    "Middle Village",
    "Oakland Gardens",
    "Ozone Park",
    "Queens Village",
    "Rego Park",
    "Richmond Hill",
    "Ridgewood",
    "Rockaway Beach",
    "Rockaway Park",
    "Rosedale",
    "South Jamaica",
    "South Ozone Park",
    "Springfield Gardens",
    "St. Albans",
    "Sunnyside",
    "Whitestone",
    "Woodhaven",
    "Woodside",
  ],
  Bronx: [
    "Baychester",
    "Bedford Park",
    "Belmont",
    "Castle Hill",
    "City Island",
    "Clason Point",
    "Co-op City",
    "Concourse",
    "Country Club",
    "East Tremont",
    "Eastchester",
    "Fordham",
    "High Bridge",
    "Hunts Point",
    "Kingsbridge",
    "Longwood",
    "Melrose",
    "Morris Heights",
    "Morris Park",
    "Morrisania",
    "Mott Haven",
    "Norwood",
    "Parkchester",
    "Pelham Bay",
    "Pelham Gardens",
    "Port Morris",
    "Riverdale",
    "Soundview",
    "South Bronx",
    "Throgs Neck",
    "Tremont",
    "University Heights",
    "Van Nest",
    "Wakefield",
    "West Farms",
    "Westchester Square",
    "Williamsbridge",
    "Woodlawn",
  ],
  "Staten Island": [
    "Annadale",
    "Arden Heights",
    "Bulls Head",
    "Castleton Corners",
    "Charleston",
    "Dongan Hills",
    "Eltingville",
    "Emerson Hill",
    "Fox Hills",
    "Graniteville",
    "Grant City",
    "Great Kills",
    "Grymes Hill",
    "Huguenot",
    "Livingston",
    "Manor Heights",
    "Mariners Harbor",
    "Midland Beach",
    "New Brighton",
    "New Dorp",
    "New Springville",
    "Oakwood",
    "Pleasant Plains",
    "Port Richmond",
    "Prince's Bay",
    "Richmondtown",
    "Rosebank",
    "Rossville",
    "Shore Acres",
    "Silver Lake",
    "South Beach",
    "St. George",
    "Stapleton",
    "Sunnyside",
    "Todt Hill",
    "Tompkinsville",
    "Tottenville",
    "Travis",
    "West Brighton",
    "Westerleigh",
    "Willowbrook",
    "Woodrow",
  ],
};

// Flat list of all neighborhoods for backward compatibility
export const NYC_NEIGHBORHOODS = Object.values(BOROUGH_NEIGHBORHOODS).flat().sort();

export const BUILDING_TYPES = [
  "Pre-war",
  "Post-war",
  "High-rise",
  "Walk-up",
  "Brownstone",
  "Townhouse",
  "New Construction",
  "Condo",
  "Co-op",
  "Rental",
];
